{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-template.fullname" . }}
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.stringData }}
  {{- toYaml .Values.secret.stringData | nindent 2 }}
  {{- else }}
  {}
  {{- end }}
{{- end }}
